// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRZCpOChDuPm-XuIVRL95UCiHJ3Vt69k',
    appId: '1:966826657989:web:e0a3000cd9d07090dcc8ac',
    messagingSenderId: '966826657989',
    projectId: 'easy-chat-84b64',
    authDomain: 'easy-chat-84b64.firebaseapp.com',
    databaseURL: 'https://easy-chat-84b64-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'easy-chat-84b64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALkiNMpJD-PVevrs7nuFck1HMkNtS00Bc',
    appId: '1:966826657989:android:b0e87c5f71476973dcc8ac',
    messagingSenderId: '966826657989',
    projectId: 'easy-chat-84b64',
    databaseURL: 'https://easy-chat-84b64-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'easy-chat-84b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdz8l4U8UIw7j2IC_A9XQUUNG3drcfbVw',
    appId: '1:966826657989:ios:f055302dc87e4394dcc8ac',
    messagingSenderId: '966826657989',
    projectId: 'easy-chat-84b64',
    databaseURL: 'https://easy-chat-84b64-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'easy-chat-84b64.appspot.com',
    androidClientId: '966826657989-c84gbqahsn3cq8ge9o8kq18lt2f8pq4b.apps.googleusercontent.com',
    iosClientId: '966826657989-imkb6pne631ibcc2h3dge2dhja3rji24.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoCalling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdz8l4U8UIw7j2IC_A9XQUUNG3drcfbVw',
    appId: '1:966826657989:ios:9e3d83bf0adf15d3dcc8ac',
    messagingSenderId: '966826657989',
    projectId: 'easy-chat-84b64',
    databaseURL: 'https://easy-chat-84b64-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'easy-chat-84b64.appspot.com',
    androidClientId: '966826657989-c84gbqahsn3cq8ge9o8kq18lt2f8pq4b.apps.googleusercontent.com',
    iosClientId: '966826657989-munbmpkagcf1veqvdj8g7gfdg4ld2ta9.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoCalling.RunnerTests',
  );
}
